phrase=input("enter the first line of a nursery rhyme:")
length=len(phrase)
print("this has",length,"letters in it")
start=int(input("enter a starting number:"))
end=int(input("pon un numero final:"))
part=(phrase[start:end])
print(part)
